In [1]:
import pandas as pd
import numpy as np
import scipy.stats as st
import os

In [9]:
# Read in the data.
df = pd.read_csv('data_iris.csv', header='infer')

In [11]:
df.shape

(150, 5)

In [13]:
df.head(3)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

In [15]:
# Set aside two variables.
x = df['Petal.Length']
y = df['Sepal.Length']

In [25]:
# Using the SciPy function.
# Correlation and p-value.
np.round(st.pearsonr(x,y),3)

array([0.872, 0.   ])

In [23]:
# Using the Pandas function.
x.corr(y)

0.8717537758865832

In [21]:
# Correlation array.
np.round(df.corr(),3)

ValueError: could not convert string to float: 'setosa'

In [27]:
# Using the SciPy function.
# Correlation and p-value.
np.round(st.spearmanr(x,y),3)

array([0.882, 0.   ])

In [29]:
# Using the SciPy function.
# Correlation and p-value.
np.round(st.kendalltau(x,y),3)

array([0.719, 0.   ])

In [31]:
 # Read in another data set.
df = pd.read_csv('data_studentlist.csv', header='infer')

In [33]:
df.head(3)

name gender  age  grade absence bloodtype  height  weight
0   Jared Diamond      M   23      3       Y         O   165.3    68.2
1  Sarah O'Donnel      F   22      2       N        AB   170.1    53.0
2    Brian Martin      M   24      4       N         B   175.0    80.1

In [35]:
# Set aside two variables.
x = df.height
y = df.weight

In [37]:
# Apply the Fisher's z-transformation.
# See the lecture.
n = len(x)
r = x.corr(y)
z = np.arctanh(r)
std_error_z = 1/np.sqrt(n-3)

In [39]:
# 95% confidence interval.
# Expressed as a dictionary object.
{'low':np.tanh(z-st.norm.ppf(0.975)*std_error_z), 'high': np.tanh(z+st.norm.ppf(0.975)*std_error_z)}

{'low': 0.26960396330592235, 'high': 0.8677953581441814}

In [41]:
# 99% confidence interval.
# Expressed as a dictionary object.
{'low':np.tanh(z-st.norm.ppf(0.995)*std_error_z), 'high': np.tanh(z+st.norm.ppf(0.995)*std_error_z)}

{'low': 0.11137578298592958, 'high': 0.9030812794020874}